/// Structured explanation for a recommendation.
///
/// Answers the four key questions:
/// - Why this?
/// - Why now?
/// - What improves?
/// - What happens after completion?
///
/// Generated by [RecommendationRule] implementations using deterministic
/// templates — no AI or LLM involvement.
class RecommendationReason {
  const RecommendationReason({
    required this.why,
    required this.whyNow,
    required this.improvement,
    this.unlock = '',
    this.template = '',
  });

  /// "Why this?" — The reason this specific recommendation was chosen.
  final String why;

  /// "Why now?" — Why this is relevant right now.
  final String whyNow;

  /// "What improves?" — The expected outcome or growth dimension.
  final String improvement;

  /// "What happens after completion?" — What becomes available next.
  final String unlock;

  /// Which template generated this reason (for traceability).
  final String template;

  /// Full explanation string combining all parts.
  String get fullExplanation => '$why $whyNow $improvement';

  @override
  String toString() =>
      'RecommendationReason(template: $template, why: $why)';
}
