import 'dart:convert';

/// A growth recommendation generated by the Personal Knowledge Engine.
///
/// Recommendations are actionable suggestions for the user to
/// grow their knowledge, close skill gaps, or pursue new domains.
class KnowledgeRecommendation {
  const KnowledgeRecommendation({
    required this.id,
    required this.type,
    required this.title,
    this.description,
    this.relevance = 0.5,
    this.urgency = 0.5,
    this.sourceNodeIds = const [],
    this.targetNodeIds = const [],
    this.metadata = const {},
    this.createdAt,
  });

  /// Unique identifier.
  final String id;

  /// Type of recommendation.
  final KnowledgeRecommendationType type;

  /// Short title.
  final String title;

  /// Detailed description.
  final String? description;

  /// Relevance to the user's goals (0.0 - 1.0).
  final double relevance;

  /// Urgency level (0.0 - 1.0).
  final double urgency;

  /// IDs of source knowledge nodes (e.g., current skills).
  final List<String> sourceNodeIds;

  /// IDs of target knowledge nodes (e.g., skills to acquire).
  final List<String> targetNodeIds;

  /// Additional metadata.
  final Map<String, dynamic> metadata;

  /// When this recommendation was generated.
  final DateTime? createdAt;

  RecommendationPriority get priority {
    final score = (relevance + urgency) / 2;
    if (score >= 0.7) return RecommendationPriority.high;
    if (score >= 0.4) return RecommendationPriority.medium;
    return RecommendationPriority.low;
  }

  KnowledgeRecommendation copyWith({
    String? id,
    KnowledgeRecommendationType? type,
    String? title,
    String? description,
    double? relevance,
    double? urgency,
    List<String>? sourceNodeIds,
    List<String>? targetNodeIds,
    Map<String, dynamic>? metadata,
    DateTime? createdAt,
  }) {
    return KnowledgeRecommendation(
      id: id ?? this.id,
      type: type ?? this.type,
      title: title ?? this.title,
      description: description ?? this.description,
      relevance: relevance ?? this.relevance,
      urgency: urgency ?? this.urgency,
      sourceNodeIds: sourceNodeIds ?? this.sourceNodeIds,
      targetNodeIds: targetNodeIds ?? this.targetNodeIds,
      metadata: metadata ?? this.metadata,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'type': type.name,
      'title': title,
      'description': description,
      'relevance': relevance,
      'urgency': urgency,
      'sourceNodeIds': sourceNodeIds,
      'targetNodeIds': targetNodeIds,
      'metadata': metadata,
      'createdAt': createdAt?.toIso8601String(),
    };
  }

  factory KnowledgeRecommendation.fromMap(Map<String, dynamic> map) {
    return KnowledgeRecommendation(
      id: map['id'] as String,
      type: KnowledgeRecommendationType.fromString(
          map['type'] as String? ?? 'nextAction'),
      title: map['title'] as String? ?? '',
      description: map['description'] as String?,
      relevance: (map['relevance'] as num?)?.toDouble() ?? 0.5,
      urgency: (map['urgency'] as num?)?.toDouble() ?? 0.5,
      sourceNodeIds:
          List<String>.from(map['sourceNodeIds'] as List? ?? []),
      targetNodeIds:
          List<String>.from(map['targetNodeIds'] as List? ?? []),
      metadata: Map<String, dynamic>.from(map['metadata'] as Map? ?? {}),
      createdAt: map['createdAt'] != null
          ? DateTime.tryParse(map['createdAt'] as String)
          : null,
    );
  }

  String toJson() => json.encode(toMap());
  factory KnowledgeRecommendation.fromJson(String source) =>
      KnowledgeRecommendation.fromMap(
          json.decode(source) as Map<String, dynamic>);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeRecommendation && other.id == id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() =>
      'KnowledgeRecommendation($type: $title, priority: $priority)';
}

/// Types of knowledge recommendations.
enum KnowledgeRecommendationType {
  skillGap('Skill Gap', 'Acquire a missing skill'),
  nextAction('Next Action', 'Take the next learning step'),
  learningPath('Learning Path', 'Follow a structured learning path'),
  careerMove('Career Move', 'Career development opportunity'),
  projectIdea('Project Idea', 'Build something to apply knowledge'),
  mentorship('Mentorship', 'Connect with a mentor'),
  resource('Resource', 'Book, course, or article recommendation'),
  milestone('Milestone', 'Celebrate a knowledge milestone'),
  custom('Custom', 'User-defined recommendation');

  const KnowledgeRecommendationType(this.label, this.description);

  final String label;
  final String description;

  static KnowledgeRecommendationType fromString(String value) {
    return KnowledgeRecommendationType.values.firstWhere(
      (t) => t.name == value,
      orElse: () => KnowledgeRecommendationType.custom,
    );
  }
}

/// Priority level for recommendations.
enum RecommendationPriority { low, medium, high }
