import 'dart:convert';

/// An insight discovered by the Personal Knowledge Engine.
///
/// Generated by [PersonalKnowledgeEngine.analyze].
/// Represents findings like skill gaps, goal conflicts,
/// learning opportunities, and growth patterns.
class KnowledgeInsight {
  const KnowledgeInsight({
    required this.id,
    required this.type,
    required this.title,
    this.description,
    this.nodeIds = const [],
    this.relevance = 0.5,
    this.actionable = false,
    this.metadata = const {},
    this.createdAt,
  });

  /// Unique identifier.
  final String id;

  /// Type of insight.
  final KnowledgeInsightType type;

  /// Short title.
  final String title;

  /// Detailed description.
  final String? description;

  /// IDs of related knowledge nodes.
  final List<String> nodeIds;

  /// Relevance score (0.0 - 1.0).
  final double relevance;

  /// Whether this insight suggests an action.
  final bool actionable;

  /// Additional metadata.
  final Map<String, dynamic> metadata;

  /// When this insight was generated.
  final DateTime? createdAt;

  KnowledgeInsight copyWith({
    String? id,
    KnowledgeInsightType? type,
    String? title,
    String? description,
    List<String>? nodeIds,
    double? relevance,
    bool? actionable,
    Map<String, dynamic>? metadata,
    DateTime? createdAt,
  }) {
    return KnowledgeInsight(
      id: id ?? this.id,
      type: type ?? this.type,
      title: title ?? this.title,
      description: description ?? this.description,
      nodeIds: nodeIds ?? this.nodeIds,
      relevance: relevance ?? this.relevance,
      actionable: actionable ?? this.actionable,
      metadata: metadata ?? this.metadata,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'type': type.name,
      'title': title,
      'description': description,
      'nodeIds': nodeIds,
      'relevance': relevance,
      'actionable': actionable,
      'metadata': metadata,
      'createdAt': createdAt?.toIso8601String(),
    };
  }

  factory KnowledgeInsight.fromMap(Map<String, dynamic> map) {
    return KnowledgeInsight(
      id: map['id'] as String,
      type: KnowledgeInsightType.fromString(
          map['type'] as String? ?? 'pattern'),
      title: map['title'] as String? ?? '',
      description: map['description'] as String?,
      nodeIds: List<String>.from(map['nodeIds'] as List? ?? []),
      relevance: (map['relevance'] as num?)?.toDouble() ?? 0.5,
      actionable: map['actionable'] as bool? ?? false,
      metadata: Map<String, dynamic>.from(map['metadata'] as Map? ?? {}),
      createdAt: map['createdAt'] != null
          ? DateTime.tryParse(map['createdAt'] as String)
          : null,
    );
  }

  String toJson() => json.encode(toMap());
  factory KnowledgeInsight.fromJson(String source) =>
      KnowledgeInsight.fromMap(
          json.decode(source) as Map<String, dynamic>);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeInsight && other.id == id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() =>
      'KnowledgeInsight($type: $title, relevance: $relevance)';
}

/// Types of knowledge insights.
enum KnowledgeInsightType {
  skillGap('Skill Gap', 'Missing skills that would help growth'),
  strength('Strength', 'Recognized area of strength'),
  learningOpportunity(
      'Learning Opportunity', 'A topic worth exploring further'),
  goalConflict('Goal Conflict', 'Goals that may conflict'),
  pattern('Pattern', 'Observed learning or growth pattern'),
  coverage('Coverage', 'Domain coverage analysis'),
  cluster('Cluster', 'Related knowledge cluster'),
  recommendation('Recommendation', 'Suggested next action'),
  custom('Custom', 'User-defined insight type');

  const KnowledgeInsightType(this.label, this.description);

  final String label;
  final String description;

  static KnowledgeInsightType fromString(String value) {
    return KnowledgeInsightType.values.firstWhere(
      (t) => t.name == value,
      orElse: () => KnowledgeInsightType.custom,
    );
  }
}
