import 'identity_profile.dart';

/// Read-only snapshot of the user's current identity state.
///
/// Consumers (Dashboard, AI Mentor, Recommendation Engine, etc.) read this
/// snapshot instead of querying multiple services directly.
///
/// Immutable. Generated by [IdentityEngine.buildSnapshot].
class IdentitySnapshot {
  const IdentitySnapshot({
    required this.profile,
    required this.currentIdentityTitle,
    required this.targetIdentityTitle,
    required this.currentGoal,
    required this.experience,
    required this.progress,
    required this.currentMissionTitle,
    required this.currentLearningPathTitle,
    required this.currentCareerPathTitle,
    required this.growthIndex,
    required this.completionPercent,
    required this.lastUpdated,
    this.missionCount = 0,
    this.completedMissions = 0,
    this.lessonCount = 0,
    this.completedLessons = 0,
    this.totalXp = 0,
    this.level = 1,
    this.activeHabitCount = 0,
    this.knowledgeNodeCount = 0,
    this.hasActiveMission = false,
    this.hasActiveLearning = false,
  });

  /// The full identity profile.
  final IdentityProfile profile;

  /// User-friendly title of the current identity (e.g. "Software Engineer").
  final String currentIdentityTitle;

  /// User-friendly title of the target identity.
  final String targetIdentityTitle;

  /// The user's current goal description.
  final String currentGoal;

  /// Experience level label (e.g. "Intermediate").
  final String experience;

  /// Quantitative progress description (e.g. "Level 3 of 7").
  final String progress;

  /// Title of the current active mission, or empty string.
  final String currentMissionTitle;

  /// Title of the current learning path, or empty string.
  final String currentLearningPathTitle;

  /// Title of the current career path, or empty string.
  final String currentCareerPathTitle;

  /// Placeholder growth index (0.0–1.0) for future intelligence.
  final double growthIndex;

  /// Overall completion percentage (0–100).
  final int completionPercent;

  /// When this snapshot was generated.
  final DateTime lastUpdated;

  // ── Optional Quantifiers ───────────────────────────────────────────

  /// Total mission count.
  final int missionCount;

  /// Completed mission count.
  final int completedMissions;

  /// Total lesson count.
  final int lessonCount;

  /// Completed lesson count.
  final int completedLessons;

  /// Total XP earned.
  final int totalXp;

  /// Current level.
  final int level;

  /// Number of active habits.
  final int activeHabitCount;

  /// Number of knowledge graph nodes.
  final int knowledgeNodeCount;

  /// Whether there is an active mission.
  final bool hasActiveMission;

  /// Whether there is an active learning path.
  final bool hasActiveLearning;

  // ── Computed ───────────────────────────────────────────────────────

  /// Whether this snapshot has minimal data (new user).
  bool get isNewUser =>
      missionCount == 0 &&
      lessonCount == 0 &&
      totalXp == 0 &&
      !hasActiveMission &&
      !hasActiveLearning;

  /// Whether the user has made any progress.
  bool get hasAnyProgress =>
      missionCount > 0 || lessonCount > 0 || totalXp > 0;

  /// Mission completion rate as a fraction (0.0–1.0).
  double get missionCompletionRate =>
      missionCount > 0 ? completedMissions / missionCount : 0.0;

  /// Lesson completion rate as a fraction (0.0–1.0).
  double get lessonCompletionRate =>
      lessonCount > 0 ? completedLessons / lessonCount : 0.0;

  /// Returns a short status label for the user.
  String get statusLabel {
    if (isNewUser) return 'Getting Started';
    if (completionPercent >= 100) return 'Journey Complete';
    if (hasActiveMission && hasActiveLearning) return 'Active Growth';
    if (hasActiveMission) return 'On a Mission';
    if (hasActiveLearning) return 'Learning';
    return 'Building Momentum';
  }

  @override
  String toString() =>
      'IdentitySnapshot(identity: $currentIdentityTitle, '
      'completion: $completionPercent%, goal: $currentGoal, '
      'lastUpdated: $lastUpdated)';
}
