/// Metadata attached to every AI-generated content item.
///
/// Tracks provenance, versioning, and confidence so that Phoenix can:
/// - Distinguish AI-generated from user-created content
/// - Support rollback and clear operations
/// - Detect duplicates via contentHash
/// - Support future schema migrations
///
/// **Invariant:** Every AI-generated object in any domain engine MUST carry
/// an [AIContentMetadata] with `source == sourceAI`.
class AIContentMetadata {
  const AIContentMetadata({
    required this.source,
    required this.provider,
    required this.promptVersion,
    required this.schemaVersion,
    required this.generatedAt,
    required this.contextVersion,
    required this.confidenceScore,
    required this.contentHash,
  });

  /// Constant indicating AI-generated content.
  static const String sourceAI = 'ai';

  /// Constant indicating user-created content.
  static const String sourceUser = 'user';

  /// Content source (ai, user, imported).
  final String source;

  /// AI provider name (e.g., 'gemini', 'openAI', 'deepSeek').
  final String provider;

  /// Version of the prompt template used to generate this content.
  final String promptVersion;

  /// Schema version of the content structure.
  final int schemaVersion;

  /// When this content was generated.
  final DateTime generatedAt;

  /// Context version snapshot used during generation.
  final int contextVersion;

  /// Confidence score from the AI Response Gateway (0.0–1.0).
  final double confidenceScore;

  /// Hash of the content for duplicate detection.
  final String contentHash;

  /// Whether this content was generated by AI.
  bool get isAIGenerated => source == sourceAI;

  /// Whether this content was created by the user.
  bool get isUserCreated => source == sourceUser;

  /// Returns a copy with the given fields replaced.
  AIContentMetadata copyWith({
    String? source,
    String? provider,
    String? promptVersion,
    int? schemaVersion,
    DateTime? generatedAt,
    int? contextVersion,
    double? confidenceScore,
    String? contentHash,
  }) =>
      AIContentMetadata(
        source: source ?? this.source,
        provider: provider ?? this.provider,
        promptVersion: promptVersion ?? this.promptVersion,
        schemaVersion: schemaVersion ?? this.schemaVersion,
        generatedAt: generatedAt ?? this.generatedAt,
        contextVersion: contextVersion ?? this.contextVersion,
        confidenceScore: confidenceScore ?? this.confidenceScore,
        contentHash: contentHash ?? this.contentHash,
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AIContentMetadata && contentHash == other.contentHash;

  @override
  int get hashCode => contentHash.hashCode;

  @override
  String toString() =>
      'AIContentMetadata(source: $source, provider: $provider, '
      'schema: $schemaVersion, confidence: $confidenceScore)';
}
