/// Type of career opportunity.
enum OpportunityType {
  fullTimeJob('Full-Time'),
  internship('Internship'),
  freelance('Freelance'),
  openSource('Open Source'),
  certification('Certification'),
  startup('Startup'),
  hackathon('Hackathon');

  const OpportunityType(this.label);
  final String label;
}

/// Immutable representation of a recommended career opportunity.
///
/// Generated by the Opportunity Engine. Not a job board — it's a
/// recommendation derived from the user's Journey, Portfolio, Resume,
/// Interview readiness, Career Profile, Decision, and Identity.
class Opportunity {
  const Opportunity({
    required this.id,
    required this.title,
    this.type = OpportunityType.fullTimeJob,
    this.matchScore = 0.0,
    this.requiredSkills = const [],
    this.matchedSkills = const [],
    this.missingSkills = const [],
    this.estimatedReadiness = '',
    this.recommendedActions = const [],
    this.estimatedTimeline = '',
    this.description = '',
  });

  /// Unique identifier.
  final String id;

  /// Human-readable opportunity title (e.g. 'Junior Flutter Developer').
  final String title;

  /// Type of opportunity.
  final OpportunityType type;

  /// Match score from 0.0 to 1.0.
  final double matchScore;

  /// Skills required for this opportunity.
  final List<String> requiredSkills;

  /// Skills the user already matches.
  final List<String> matchedSkills;

  /// Skills the user is missing.
  final List<String> missingSkills;

  /// Estimated readiness level (e.g. 'Nearly Ready', 'Building').
  final String estimatedReadiness;

  /// Recommended actions to improve readiness.
  final List<String> recommendedActions;

  /// Estimated timeline (e.g. '4 weeks', '2 months').
  final String estimatedTimeline;

  /// Short description of the opportunity.
  final String description;

  /// Serializes to a JSON-compatible map.
  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'id': id,
      'title': title,
      'type': type.name,
      'matchScore': matchScore,
      'requiredSkills': requiredSkills,
      'matchedSkills': matchedSkills,
      'missingSkills': missingSkills,
      'estimatedReadiness': estimatedReadiness,
      'recommendedActions': recommendedActions,
      'estimatedTimeline': estimatedTimeline,
      'description': description,
    };
  }

  /// Creates from a JSON-compatible map.
  factory Opportunity.fromMap(Map<String, dynamic> map) {
    return Opportunity(
      id: map['id'] as String,
      title: map['title'] as String,
      type: OpportunityType.values.firstWhere(
        (t) => t.name == map['type'],
        orElse: () => OpportunityType.fullTimeJob,
      ),
      matchScore: (map['matchScore'] as num?)?.toDouble() ?? 0.0,
      requiredSkills: map['requiredSkills'] != null
          ? List<String>.from(map['requiredSkills'] as List)
          : const [],
      matchedSkills: map['matchedSkills'] != null
          ? List<String>.from(map['matchedSkills'] as List)
          : const [],
      missingSkills: map['missingSkills'] != null
          ? List<String>.from(map['missingSkills'] as List)
          : const [],
      estimatedReadiness: map['estimatedReadiness'] as String? ?? '',
      recommendedActions: map['recommendedActions'] != null
          ? List<String>.from(map['recommendedActions'] as List)
          : const [],
      estimatedTimeline: map['estimatedTimeline'] as String? ?? '',
      description: map['description'] as String? ?? '',
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is Opportunity && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() =>
      'Opportunity(id: $id, title: $title, score: $matchScore)';
}
