import 'dart:convert';

/// An insight or recommendation generated by the Habit Intelligence Engine.
///
/// Immutable. Insights are produced from behaviour analysis and can
/// be enhanced by AIMentorService for natural language explanations.
class HabitInsight {
  const HabitInsight({
    required this.id,
    required this.habitId,
    required this.title,
    this.description,
    this.type = InsightType.observation,
    this.priority = InsightPriority.normal,
    this.createdAt,
    this.actionable = false,
    this.actionLabel,
  });

  /// Unique identifier.
  final String id;

  /// ID of the related habit (or 'overall' for general insights).
  final String habitId;

  /// Short title (e.g. "Streak at Risk", "Great Consistency!").
  final String title;

  /// Detailed description or explanation.
  final String? description;

  /// Category of insight.
  final InsightType type;

  /// Importance level.
  final InsightPriority priority;

  /// When this insight was generated.
  final DateTime? createdAt;

  /// Whether this insight suggests an actionable step.
  final bool actionable;

  /// Label for the action button (e.g. "Adjust Schedule", "Set Reminder").
  final String? actionLabel;

  HabitInsight copyWith({
    String? id,
    String? habitId,
    String? title,
    String? description,
    InsightType? type,
    InsightPriority? priority,
    DateTime? createdAt,
    bool? actionable,
    String? actionLabel,
    bool clearDescription = false,
    bool clearActionLabel = false,
  }) {
    return HabitInsight(
      id: id ?? this.id,
      habitId: habitId ?? this.habitId,
      title: title ?? this.title,
      description: clearDescription ? null : (description ?? this.description),
      type: type ?? this.type,
      priority: priority ?? this.priority,
      createdAt: createdAt ?? this.createdAt,
      actionable: actionable ?? this.actionable,
      actionLabel: clearActionLabel ? null : (actionLabel ?? this.actionLabel),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'habitId': habitId,
      'title': title,
      'description': description,
      'type': type.name,
      'priority': priority.name,
      'createdAt': createdAt?.toIso8601String(),
      'actionable': actionable,
      'actionLabel': actionLabel,
    };
  }

  factory HabitInsight.fromMap(Map<String, dynamic> map) {
    return HabitInsight(
      id: map['id'] as String,
      habitId: map['habitId'] as String? ?? 'overall',
      title: map['title'] as String? ?? '',
      description: map['description'] as String?,
      type: InsightType.fromString(map['type'] as String? ?? 'observation'),
      priority:
          InsightPriority.fromString(map['priority'] as String? ?? 'normal'),
      createdAt: map['createdAt'] != null
          ? DateTime.parse(map['createdAt'] as String)
          : null,
      actionable: map['actionable'] as bool? ?? false,
      actionLabel: map['actionLabel'] as String?,
    );
  }

  String toJson() => json.encode(toMap());
  factory HabitInsight.fromJson(String source) =>
      HabitInsight.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is HabitInsight && other.id == id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() =>
      'HabitInsight(id: $id, title: $title, type: $type, priority: $priority)';
}

/// Category of habit insight.
enum InsightType {
  /// General observation about behaviour.
  observation,

  /// Positive reinforcement for good habits.
  encouragement,

  /// Warning about declining consistency.
  warning,

  /// Specific recommendation for improvement.
  recommendation,

  /// Streak-related insight.
  streak,

  /// Consistency-related insight.
  consistency,

  /// Trend-related insight.
  trend,

  /// Goal progress insight.
  goal;

  String get label {
    switch (this) {
      case InsightType.observation:
        return 'Observation';
      case InsightType.encouragement:
        return 'Encouragement';
      case InsightType.warning:
        return 'Warning';
      case InsightType.recommendation:
        return 'Recommendation';
      case InsightType.streak:
        return 'Streak';
      case InsightType.consistency:
        return 'Consistency';
      case InsightType.trend:
        return 'Trend';
      case InsightType.goal:
        return 'Goal Progress';
    }
  }

  static InsightType fromString(String value) {
    return InsightType.values.firstWhere(
      (t) => t.name == value,
      orElse: () => InsightType.observation,
    );
  }
}

/// Priority level for insights.
enum InsightPriority {
  low,
  normal,
  high,
  critical;

  String get label {
    switch (this) {
      case InsightPriority.low:
        return 'Low';
      case InsightPriority.normal:
        return 'Normal';
      case InsightPriority.high:
        return 'High';
      case InsightPriority.critical:
        return 'Critical';
    }
  }

  static InsightPriority fromString(String value) {
    return InsightPriority.values.firstWhere(
      (p) => p.name == value,
      orElse: () => InsightPriority.normal,
    );
  }
}
