/// Types of reviews generated by the Review Engine.
enum ReviewType {
  daily('Daily Review', 'End-of-day summary'),
  weekly('Weekly Review', 'End-of-week progress report'),
  monthly('Monthly Review', 'Monthly growth assessment'),
  career('Career Review', 'Career trajectory evaluation'),
  growth('Growth Review', 'Multi-dimension growth analysis'),
  learning('Learning Review', 'Learning progress assessment'),
  interview('Interview Review', 'Interview readiness evaluation'),
  portfolio('Portfolio Review', 'Portfolio completeness review'),
  opportunity('Opportunity Review', 'Opportunity pipeline review');

  const ReviewType(this.displayName, this.description);
  final String displayName;
  final String description;
}

/// A single review item with score and recommendation.
class ReviewItem {
  const ReviewItem({
    required this.category,
    required this.score,
    required this.summary,
    this.strengths = const [],
    this.weaknesses = const [],
    this.recommendations = const [],
  });

  final String category;
  final double score;
  final String summary;
  final List<String> strengths;
  final List<String> weaknesses;
  final List<String> recommendations;

  ReviewItem copyWith({
    String? category,
    double? score,
    String? summary,
    List<String>? strengths,
    List<String>? weaknesses,
    List<String>? recommendations,
  }) =>
      ReviewItem(
        category: category ?? this.category,
        score: score ?? this.score,
        summary: summary ?? this.summary,
        strengths: strengths ?? this.strengths,
        weaknesses: weaknesses ?? this.weaknesses,
        recommendations: recommendations ?? this.recommendations,
      );

  Map<String, dynamic> toMap() => {
        'category': category,
        'score': score,
        'summary': summary,
        'strengths': strengths,
        'weaknesses': weaknesses,
        'recommendations': recommendations,
      };

  factory ReviewItem.fromMap(Map<String, dynamic> map) => ReviewItem(
        category: map['category'] as String? ?? '',
        score: (map['score'] as num?)?.toDouble() ?? 0.0,
        summary: map['summary'] as String? ?? '',
        strengths: List<String>.from(map['strengths'] ?? []),
        weaknesses: List<String>.from(map['weaknesses'] ?? []),
        recommendations: List<String>.from(map['recommendations'] ?? []),
      );
}

/// Immutable snapshot of a review for widget consumption.
class ReviewSnapshot {
  const ReviewSnapshot({
    required this.reviewType,
    required this.title,
    required this.overallScore,
    this.items = const [],
    this.date = '',
    this.periodLabel = '',
    this.overallSummary = '',
    this.topRecommendation = '',
    this.previousScore,
    this.improvement,
  });

  final ReviewType reviewType;
  final String title;
  final double overallScore;
  final List<ReviewItem> items;
  final String date;
  final String periodLabel;
  final String overallSummary;
  final String topRecommendation;
  final double? previousScore;
  final double? improvement;

  bool get hasItems => items.isNotEmpty;

  bool get isImproved =>
      previousScore != null && overallScore > previousScore!;

  double get improvementDelta =>
      previousScore != null ? overallScore - previousScore! : 0.0;

  @override
  String toString() =>
      'ReviewSnapshot(type: ${reviewType.name}, score: $overallScore, items: ${items.length})';
}
