/// A deterministic insight generated by the [DailyBriefEngine].
///
/// Insights explain why the day's tasks matter.
/// No AI or LLM involvement.
class DailyInsight {
  const DailyInsight({
    required this.message,
    required this.category,
    required this.relevance,
  });

  /// Human-readable insight message.
  final String message;

  /// Category (e.g. 'growth', 'learning', 'career', 'habit').
  final String category;

  /// Relevance score (0.0–1.0) for prioritization.
  final double relevance;

  @override
  String toString() =>
      'DailyInsight(category: $category, relevance: ${(relevance * 100).round()}%)';
}
