import 'mentor_topic.dart' show MentorTopic;

/// A single actionable suggestion from the AI mentor.
///
/// Immutable. Generated by [IntelligenceMentorService] from Phoenix
/// intelligence data. Contains a reason and evidence for explainability.
class MentorSuggestion {
  const MentorSuggestion({
    required this.id,
    required this.topic,
    required this.title,
    required this.description,
    this.reason = '',
    this.evidence = const [],
    this.confidence = 0.0,
    this.isActionable = false,
  });

  /// Unique identifier.
  final String id;

  /// Topic domain this suggestion belongs to.
  final MentorTopic topic;

  /// Short action-oriented title.
  final String title;

  /// Detailed explanation of the suggestion.
  final String description;

  /// Why this suggestion is being made.
  final String reason;

  /// Evidence strings supporting the suggestion.
  final List<String> evidence;

  /// Confidence score (0.0–1.0).
  final double confidence;

  /// Whether this requires immediate action.
  final bool isActionable;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MentorSuggestion && other.id == id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() =>
      'MentorSuggestion(id: $id, topic: $topic, title: $title)';
}
